In [21]:
import pandas as pd
import numpy as np


In [27]:
#creating 1d arrray
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
#printing odd numbers from above array

for i in a:
  if i%2 != 0 :
    print(i)

1
3
5
7
9


In [24]:
#printing odd numbers from above array

a[a%2==1]

array([1, 3, 5, 7, 9])

In [25]:
# How to replace items that satisfy a condition with another value in numpy array?

a[a%2==1]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [28]:
#How to replace items that satisfy a condition without affecting the original array?

print(np.where(a%2==1,-1,a))
a

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#  How to reshape an array?

b= a 
print(b.shape)
b.reshape(2,-1)

(10,)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
#How to stack two arrays vertically?
c = a.reshape(2,-1)
d = np.repeat(1,10).reshape(2,-1)
print(c)
print()
print(d)
print()
print(np.concatenate([c,d],axis=0))
print()
print(np.concatenate((c,d),axis=0))
print()
print(np.vstack((c,d)))

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [44]:
#How to stack two arrays horizontally?

c = a.reshape(2,-1)
d = np.repeat(1,10).reshape(2,-1)
print(np.hstack((c,d)))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [54]:
#How to generate custom sequences in numpy without hardcoding?

c = np.arange(11,21)
print(c)
np.repeat(c,3)

[11 12 13 14 15 16 17 18 19 20]


array([11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16,
       16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20])

In [56]:
#How to get the common items between two python numpy arrays?

c = np.arange(1,20,2)
d = np.arange(11,21)
print(c)
print()
np.intersect1d(c,d)


[ 1  3  5  7  9 11 13 15 17 19]



array([11, 13, 15, 17, 19])

In [57]:
#How to remove from one array those items that exist in another?
np.setdiff1d(c,d)

array([1, 3, 5, 7, 9])

In [67]:
 #How to get the positions where elements of two arrays match?
# c = np.array([1,2,3,4,5,6])
# d = np.array([3,4,5,6,7])

# print()
# print(np.where(c==d))
# print()

y = np.array([1,2,3,2,3,4,3,4,5,6])
z = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(y==z))

(array([1, 3, 5, 7]),)


In [72]:
#How to extract all numbers between a given range from a numpy array?   extract numners between any 2 numbers

c= np.arange(5,15)
print(c)
var1=int(input("Enter lower range : "))
var2 = int(input('Enter upper range : '))
index = np.where((c > var1) & (c < var2))
print(c[index])
#**************** OR ***********************

print(c[(c>7)&(c<14)])

[ 5  6  7  8  9 10 11 12 13 14]
Enter lower range : 7
Enter upper range : 14
[ 8  9 10 11 12 13]
[ 8  9 10 11 12 13]


In [76]:
#How to make a python function that handles scalars to work on numpy arrays?
c = np.array([5, 7, 9, 8, 6, 4, 5])
d = np.array([6, 3, 4, 8, 9, 7, 1])

np.where(c>d,c,d)

#**************************** OR *****************************

def maxx(a,b):
  if a >+ b:
    return a
  else:
    return b
print('New op is :- ')
maxx(c,d)

New op is :- 


ValueError: ignored

In [98]:
#some queries tried below
z = np.array([10,0,0,2],float)
print("1",z)  
print("2",np.sum(z))
print("3",(z!=0).sum())
print("4",z.sum())
print(z.size)
np.count_nonzero(z)

1 [10.  0.  0.  2.]
2 12.0
3 2
4 12.0
5 4


2

In [117]:
#row and column swapping
g = np.arange(12).reshape(4,-1)
print(g)
print()
print(g[:,0:2])
print()
g[:,[2,0]]=g[:,[0,2]]
print(g)
print()
g[[2,0],:]=g[[0,2],:]
print(g)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]

[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]

[[ 8  7  6]
 [ 5  4  3]
 [ 2  1  0]
 [11 10  9]]


In [121]:
#How to swap two rows in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
print(arr)
# Solution
print(arr[[1,2,0], : ])
arr[[1,0,2], :]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [6 7 8]
 [0 1 2]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [127]:
#reversing array

g = np.arange(0,16,2).reshape(4,-1)
h = np.array([1,2,3,4,5,6,7,8,9,0]).reshape(2,-1)

print()
print('printing g : ',g)
print()
print('printng h : ',h)

print()
print(g[::-1])
print()
print(h[::-1])


printing g :  [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]

printng h :  [[1 2 3 4 5]
 [6 7 8 9 0]]

[[12 14]
 [ 8 10]
 [ 4  6]
 [ 0  2]]

[[6 7 8 9 0]
 [1 2 3 4 5]]
