In [58]:
import numpy as np 


In [59]:
#How to create an empty and a full NumPy array?

#1. Empty array :- 
np.empty((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [60]:
#2.Full array
np.full((4,4),11,dtype=int)

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [61]:
#Create a Numpy array filled with all zeros
print(np.zeros((4,4),dtype=int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [62]:
#Create a Numpy array filled with all ones
print(np.ones((5,5),int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [63]:
# Check whether a Numpy array contains a specified row

a = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
              ])
#first we will convert array a into list using tolist and then we will check whether it is present or not
print([1, 2, 3, 4, 5] in a.tolist())
print()
print(a.reshape(1,-1))
print()
print([1, 2, 3, 4, 5] in a.reshape(1,-1))
print('******************************')
print(a.tolist())
print(a.reshape(1,-1))
print('******************************')


print()
print("So .tolist() creates a list row wise and .reshape(1,-1) creates a single list containing all the elements of array.")

True

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]

False
******************************
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
******************************

So .tolist() creates a list row wise and .reshape(1,-1) creates a single list containing all the elements of array.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  del sys.path[0]


In [64]:
#How to Remove rows in Numpy array that contains non-numeric values?

a = np.array([[1,2,3],
              [np.nan,np.nan,4],
              [5,np.nan,6]
              ])
print(a)
print('\n')
print(a[~np.isnan(a).any(axis=1)])

[[ 1.  2.  3.]
 [nan nan  4.]
 [ 5. nan  6.]]


[[1. 2. 3.]]


In [65]:
print(a[~np.isnan(a).any(axis=1)])

[[1. 2. 3.]]


In [66]:
a = np.array([
              [1,2,3,4],
              [9,8,3,4],
              [5,6,3,4]
])
print(a)
print()
b = a.tolist()
print(repr(b).count('3,4'))

[[1 2 3 4]
 [9 8 3 4]
 [5 6 3 4]]

0


In [67]:
# combining 1D and 2D array

g = np.array([1,2,3,4,5,6])

h = np.array([
              [11,22,33,44,55,66],
              [12,13,14,15,16,17],
              [22,23,24,26,27,28]
])

print(g)
print()
print(h)

[1 2 3 4 5 6]

[[11 22 33 44 55 66]
 [12 13 14 15 16 17]
 [22 23 24 26 27 28]]


In [68]:
j = g + h 
print(j)

[[12 24 36 48 60 72]
 [13 15 17 19 21 23]
 [23 25 27 30 32 34]]


In [69]:
# for a, b in np.nditer([num_1d, num_2d]):
#     print("%d:%d" % (a, b),)

for l,m in np.nditer([g,h]):
  #print("%d:%d"%(l,m))
  #print()
  print(l," : ",m)
  print()
  #print(m)

1  :  11

2  :  22

3  :  33

4  :  44

5  :  55

6  :  66

1  :  12

2  :  13

3  :  14

4  :  15

5  :  16

6  :  17

1  :  22

2  :  23

3  :  24

4  :  26

5  :  27

6  :  28



In [70]:
a1 = np.arange(5)
a2 = np.arange(6,10)

# printing combinations :-

# Method1

# import itertools as it

# a3 = it.product(a1,a2)

# for i in a3:
#   print(i,end=',')

# Method 2

a5 = np.array(np.meshgrid(a1,a2)).T.reshape(-1,2)
a5

array([[0, 6],
       [0, 7],
       [0, 8],
       [0, 9],
       [1, 6],
       [1, 7],
       [1, 8],
       [1, 9],
       [2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9]])

In [71]:
#Comparing 2 numpy arrays

a1 = np.arange(6).reshape(-1,2)
a2 =  np.arange(6).reshape(-1,2)

# MEthod 1

comp = (a1 == a2)
print(comp.all())

True


In [72]:
#check specified value are in numpy

a1 = np.arange(6).reshape(-1,2)
print(a1)
a2 = np.random.randint(1,6,(1,2))
print(a2)
print(type(a2))
print(a2 in a1)

[[0 1]
 [2 3]
 [4 5]]
[[3 1]]
<class 'numpy.ndarray'>
True


In [73]:
#formation of 3-D array and converting it into 2-D array

a1 = np.arange(3*4*2).reshape(2,3,-1)
print(a1)
a2 = np.diagonal(a1,axis1=0,axis2=1)
a2

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 0, 16],
       [ 1, 17],
       [ 2, 18],
       [ 3, 19]])

In [74]:
#flattening 2-D array

a1 = np.arange(6).reshape(-1,2)
print(a1)
a2 = a1.flatten()
a2

[[0 1]
 [2 3]
 [4 5]]


array([0, 1, 2, 3, 4, 5])

In [81]:
arr = np.zeros((2, 2, 3, 4))
print(arr)
  
gfg = np.moveaxis(arr, 0, -1).shape
  
print (gfg)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
(2, 3, 4, 2)


In [95]:
a1 = np.arange(10).reshape(-1,2)
print(a1)
print(len(a1))
print(a.shape)

print(np.count_nonzero(a1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
5
(3, 4)
9


In [98]:
print("Below statement tells us that data type of array's elements : ")
print(a1.dtype)
print("\nAnd below statement tells us what kind of structure is held in variable/container")
print(type(a1))

Below statement tells us that data type of array's elements : 
int64

And below statement tells us what kind of structure is held in variable/container
<class 'numpy.ndarray'>


In [103]:
#finding max elements

a1 = np.array([[1,2,3],[11,12,13],[32,45,77],[21,122,21]])
print(a1.max())
print(a1.min())

122
1


In [105]:
#reversing array
a1[::-1]

array([[ 21, 122,  21],
       [ 32,  45,  77],
       [ 11,  12,  13],
       [  1,   2,   3]])

In [113]:
print(a1)
print("Print element at index 5 : ",a1.take(5))
print("Elements at index 11 and 7",a1.take((11,7)))
print("Elements at index 4 and 10,3",a1.take((4,10,3)))
a1.take((3,1,7))

[[  1   2   3]
 [ 11  12  13]
 [ 32  45  77]
 [ 21 122  21]]
Print element at index 5 :  13
Elements at index 11 and 7 [21 45]
Elements at index 4 and 10,3 [ 12 122  11]


array([11,  2, 45])

In [114]:
print(a1.sum())

360
