In [1]:
import numpy as np

In [2]:
#generates an array of m*n dimenssion
data = np.random.randn(2,3)
data

array([[ 0.25115841,  0.55912237, -0.95259121],
       [ 0.33246122, -0.37984518,  0.1346203 ]])

In [4]:
data1 = np.random.randn(2,2)
data1

array([[-0.39142839, -0.94753276],
       [-2.19560217, -0.32188986]])

In [7]:
print(data*10)

[[ 2.51158408  5.59122375 -9.52591209]
 [ 3.32461221 -3.7984518   1.34620295]]


In [8]:
data.shape


(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
type(data)

numpy.ndarray

In [11]:
#creating an array 

data1 = [1,2,3,4,5,6,7,8,9]

data_array = np.array(data1)

In [12]:
data_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# creating nested array

data2 = [[1,2,3],[4]]

data_array2 = np.array(data2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """


In [21]:
print(data_array2)

[list([1, 2, 3]) list([4])]


In [20]:
data_array2.ndim

1

In [17]:
data.ndim

2

In [22]:
data_array2.shape

(2,)

In [24]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
z1 = np.zeros((3,4))

In [26]:
z1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
#l*m*n -> l = number of matrices, m = number of rows, n = number of columns
# instead of eros you can use empty() but its not compulsory that it will return 0, it can return garbage value

z2 = np.zeros((2,3,4))
z2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
z3 = np.empty((3,2))
z3

array([[ 2.51158408,  5.59122375],
       [-9.52591209,  3.32461221],
       [-3.7984518 ,  1.34620295]])

In [31]:
# range of array in numpy can be written as -> np.arange()

r1 = np.arange(19)
r1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [32]:
o = np.ones(5)
o

array([1., 1., 1., 1., 1.])

In [34]:
o1 = np.ones((3,4))
o1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [37]:
a2 = np.array([1,2,3],dtype = np.float)
a2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3.])

In [38]:
print(a1.dtype)
print(a2.dtype)

int64
float64


In [39]:
# array_name.astype(data_type) -> changes data type of array

In [40]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

numeric_value = numeric_strings.astype(float)
numeric_value

array([ 1.25, -9.6 , 42.  ])

In [45]:
numeric_strings = np.array([1.25, -9.6, 42], dtype=np.string_)
numeric_value.dtype


# even though i mentioned data type as a string but it displayed output as float........ 
# so you have to mention values inside "_".

dtype('float64')

In [51]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr1 = arr - 1
arr1

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [52]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [53]:
arr- arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [56]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [57]:
r1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [58]:
r1[5]

5

In [59]:
r2 = np.arange(4,10)
r2

array([4, 5, 6, 7, 8, 9])

In [61]:
r2[:3]

array([4, 5, 6])

In [62]:
r1_slice = r1[4:9]
r1_slice

array([4, 5, 6, 7, 8])

In [63]:
r1_slice[:] = 69
r1

array([ 0,  1,  2,  3, 69, 69, 69, 69, 69,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [67]:
r1_slice1 = r1[10:12]
r1_slice1

array([10, 11])

In [68]:
r1_slice1[:] = 99
r1

array([ 0,  1,  2,  3, 69, 69, 69, 69, 69,  9, 99, 99, 12, 13, 14, 15, 16,
       17, 18])

In [69]:
r1_slice1[:] = 33
r1

array([ 0,  1,  2,  3, 69, 69, 69, 69, 69,  9, 33, 33, 12, 13, 14, 15, 16,
       17, 18])

In [70]:
# 3-D array

In [82]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
arr3d.shape

(2, 2, 3)

In [84]:
# we have 2 matrix and printing 1st matrix 
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
acpy = arr3d[0].copy()
acpy

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr3d[0] =  69
arr3d

array([[[69, 69, 69],
        [69, 69, 69]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
arr3d[0] = acpy

In [87]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
#print 1st row from second matrix

arr3d[1,0]

array([7, 8, 9])

In [91]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [92]:
x[0]

array([7, 8, 9])