In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.arange(0,11)

b = np.arange(11,21) 

In [3]:
#How to reverse the rows of a 2D array?
c = a[::-1]
print(c)

[10  9  8  7  6  5  4  3  2  1  0]


In [4]:
#How to reverse the columns of a 2D array?

c = np.array([
              [1,2,3],
              [4,5,6],
              [8,9,0]
              ])
print(c)

print('rversing columns:\n',c[:,::-1])

[[1 2 3]
 [4 5 6]
 [8 9 0]]
rversing columns:
 [[3 2 1]
 [6 5 4]
 [0 9 8]]


In [5]:
c = np.arange(1,17)
d=c.reshape(4,-1)
print('original array : \n',d)
print()
print(d[::2])

original array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [6]:
print(d[:,:])
print()
print(d[::])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
#reversing row wise and column wise
print(d)
print()
print(d[::-1,:])
print()
print(d[:,::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [8]:
#How to create a 2D array containing random floats between 5 and 10?

d = np.random.rand(5,11)
print(d)

[[0.94932908 0.62529909 0.09916499 0.8244407  0.53124783 0.94031723
  0.85746908 0.6158548  0.12292203 0.08983298 0.48153697]
 [0.35090116 0.84507193 0.13359056 0.22121145 0.62391863 0.74667582
  0.27246975 0.78378707 0.95026822 0.44409516 0.77393806]
 [0.01421208 0.53470908 0.8239518  0.01068092 0.56975112 0.85008321
  0.65433764 0.64121328 0.41762462 0.34237162 0.51168149]
 [0.48777893 0.10137713 0.74840474 0.28083316 0.81755923 0.31314181
  0.71178651 0.14695491 0.94399065 0.09647854 0.09347378]
 [0.67291459 0.49405816 0.84294389 0.59136797 0.4578153  0.98690939
  0.81695596 0.08141039 0.55074076 0.33108865 0.0585282 ]]


In [9]:
list1 = []
d = np.random.uniform(1,10,9)
# list1.append(d)
print('printing d',d)

e = np.random.uniform(1,11,2)
print('printing e',e)
print()
print(d[1]-d[0],d[6]-d[5],d[8]-d[7])
# print(list1)

printing d [7.80309581 8.08045263 7.11348928 9.15172474 3.22791926 8.10017986
 6.41801454 9.31809503 7.63087348]
printing e [4.40808812 9.32060188]

0.2773568128825028 -1.682165316790302 -1.6872215549854177


In [10]:
print(np.random.uniform(0,1,3))

[0.45926903 0.92943373 0.30954769]


In [11]:
#How to print only 3 decimal places in python numpy array?

print(np.random.rand(5,3))

[[0.00813303 0.16753059 0.54652963]
 [0.93830904 0.81316509 0.7603557 ]
 [0.27069644 0.22545136 0.65609569]
 [0.49473301 0.24892563 0.96523984]
 [0.43266869 0.28640706 0.229732  ]]


In [12]:
rand_arr = np.random.random([5,3])
print(rand_arr)
np.set_printoptions(3)
rand_arr

[[0.97699685 0.71828429 0.69837067]
 [0.26744637 0.68517346 0.44133114]
 [0.3651645  0.94367751 0.40583398]
 [0.74228499 0.28374569 0.6668764 ]
 [0.570068   0.45213348 0.46869809]]


array([[0.977, 0.718, 0.698],
       [0.267, 0.685, 0.441],
       [0.365, 0.944, 0.406],
       [0.742, 0.284, 0.667],
       [0.57 , 0.452, 0.469]])

In [13]:
from numpy.core.arrayprint import set_printoptions
c = np.random.random([5,3])
print(a)
np.set_printoptions(3)
# print(v)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
g = np.random.randint(4,14,size=(4,5))
g

array([[13,  5,  9,  9,  9],
       [13, 13, 11, 12,  8],
       [ 9,  6,  6,  9, 10],
       [11,  9,  5,  4,  4]])

In [15]:
print(np.random.rand(5))
# np.random.rand(5,size=(3,5))

[0.656 0.327 0.826 0.487 0.872]


In [16]:

np.random.randint(0, 9,4)	

array([6, 5, 3, 7])

In [17]:
#flatening 2-D array inti 1-D array
print(g)
print()
h=g.reshape(1,-1)
np.set_printoptions(threshold=6)
print(h)


[[13  5  9  9  9]
 [13 13 11 12  8]
 [ 9  6  6  9 10]
 [11  9  5  4  4]]

[[13  5  9 ...  5  4  4]]


In [18]:
#array with zeroes

h = np.zeros((4,5),int)
j = np.ones((4,5),float)
print(j)
print(h)
print()
print(h.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

(4, 5)


In [19]:
print(np.random.randint(0,9,size=(2,3)))

[[3 7 4]
 [5 7 0]]


In [20]:
np.random.seed(2021)
np.random.rand(4)

array([0.606, 0.733, 0.139, 0.313])

In [21]:
np.random.seed(2021)


In [22]:
np.random.rand(4)

array([0.606, 0.733, 0.139, 0.313])